changelog:
  exclude:
    labels:
      - skip-changelog
      - internal
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
        - refactor
        - tests
    - title: Other Changes
      labels:
        - "*"
